# Generated by Django 4.0.4 on 2023-05-13 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_assigned_trainer_user_assigned_user_user_height_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='trainer_id',
            new_name='trainer',
        ),
    ]
