# Generated by Django 4.2 on 2023-05-24 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plan_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
