# Generated by Django 4.2 on 2023-05-24 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_user_plan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='plan_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
