# Generated by Django 4.2 on 2023-06-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_user_chatmessage_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
