# Generated by Django 4.2 on 2023-06-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_editemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='editemail',
            name='uuid',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
